[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_asset_vault = "B3G43MVazHAwnxHpg5R1u2bCUkm7FnCaMgh2ikViL7aN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
